using System;
using System.Collections;
using System.Collections.Generic;

using Unity.Services.Authentication;
using Unity.Services.Core;
using Unity.Services.Lobbies;
using Unity.Services.Lobbies.Models;
using UnityEngine;

using Random = UnityEngine.Random;


public class KitchenGameLobby : MonoBehaviour
{
    public static KitchenGameLobby Instance { get; private set; }


    public event EventHandler OnCreateLobbyStarted;
    public event EventHandler OnCreateLobbyFailed;
    public event EventHandler OnJoinStarted;
    public event EventHandler OnJoinFailed;
    public event EventHandler OnQuickJoinFailed;

    public event EventHandler<OnLobbyListChangedEventArgs> OnLobbyListChanged;
    public class OnLobbyListChangedEventArgs : EventArgs
    {
        public List<Lobby> LobbyList;
    }


    private Lobby _JoinedLobby;
    private float _HeartbeatTimer;
    private float _HeartbeatTimerMax = 15f;
    private float _LobbyListUpdatesTimer;
    private float _LobbyListUpdatesTimerMax = 3f;



    private void Awake()
    {
        Instance = this;

        DontDestroyOnLoad(gameObject);

        InitializeUnityAuthentication();
    }

    private void Update()
    {
        HandleHeartbeat();
        HandlePeriodicLobbiesListUpdates();
    }

    private async void InitializeUnityAuthentication()
    {
        // Initialize UnityServices if necessary.
        // This prevents us from trying to do it again after the player has returned
        // to the main menu and then tried to go in-game again, which would cause an error.
        if (UnityServices.State != ServicesInitializationState.Initialized)
        {
            InitializationOptions initializationOptions = new InitializationOptions();

            // Create a random profile name. We are generating random profiles, because
            // otherwise we can't test with multiple builds running on the same PC,
            // as they would have the same player ID then (which is generated by the
            // AuthenticationService).
            initializationOptions.SetProfile(Random.Range(0, 10001).ToString());

            await UnityServices.InitializeAsync();

            // This line is only necessary for test builds of the game.
            // WARNING: It MUST be commented out or removed in final builds of the game, or players will lose their account information every time.
            // Basically, this forces it to create a new login credential, ensuring that each instance of your test build of the game has its own
            // unique login credentials. Otherwise, the client log will have an error with an exception rethrown saying the player is already a
            // member of the lobby it tried to join.
            //AuthenticationService.Instance.ClearSessionToken();

            await AuthenticationService.Instance.SignInAnonymouslyAsync();
        }
    }

    private void HandleHeartbeat()
    {
        if (IsLobbyHost())
        {

            _HeartbeatTimer -= Time.deltaTime;
            if (_HeartbeatTimer < 0)
            {
                _HeartbeatTimer = _HeartbeatTimerMax;
                LobbyService.Instance.SendHeartbeatPingAsync(_JoinedLobby.Id);
            }
        }
    }

    private void HandlePeriodicLobbiesListUpdates()
    {
        if (_JoinedLobby == null && AuthenticationService.Instance.IsSignedIn)
        {
            _LobbyListUpdatesTimer -= Time.deltaTime;
            if (_LobbyListUpdatesTimer <= 0)
            {
                _LobbyListUpdatesTimer = _LobbyListUpdatesTimerMax;

                GetLobbiesList();
            }
        }
    }

    private bool IsLobbyHost()
    {
        return _JoinedLobby != null && _JoinedLobby.HostId == AuthenticationService.Instance.PlayerId;
    }

    private async void GetLobbiesList()
    {
        try
        {
            QueryLobbiesOptions queryLobbiesOptions = new QueryLobbiesOptions
            {
                Filters = new List<QueryFilter>
                {
                    // This filter only accepts lobbies with at least one open player slot left.
                    new QueryFilter(QueryFilter.FieldOptions.AvailableSlots, "0", QueryFilter.OpOptions.GT),
                }
            };


            QueryResponse queryResponse = await LobbyService.Instance.QueryLobbiesAsync(queryLobbiesOptions);

            OnLobbyListChanged?.Invoke(this, new OnLobbyListChangedEventArgs
            {
                LobbyList = queryResponse.Results,
            });
        }
        catch (LobbyServiceException e)
        {
            Debug.LogException(e);
        }
    }

    public async void CreateLobby(string lobbyName, bool isPrivate)
    {
        OnCreateLobbyStarted?.Invoke(this, EventArgs.Empty);

        try
        {
            _JoinedLobby = await LobbyService.Instance.CreateLobbyAsync(lobbyName, KitchenGameMultiplayer.MAX_PLAYERS_AMOUNT,
                                                                        new CreateLobbyOptions { IsPrivate = isPrivate });

            KitchenGameMultiplayer.Instance.StartHost();
            Loader.LoadSceneMultiplayer(Loader.Scenes.CharacterSelectScene);
        }
        catch (LobbyServiceException e)
        {
            Debug.LogException(e);
            OnCreateLobbyFailed?.Invoke(this, EventArgs.Empty);
        }
    }

    public async void QuickJoin()
    {
        OnJoinStarted?.Invoke(this, EventArgs.Empty);

        try
        {
            _JoinedLobby = await LobbyService.Instance.QuickJoinLobbyAsync();

            KitchenGameMultiplayer.Instance.StartClient();
        }
        catch (LobbyServiceException e)
        {
            Debug.LogException(e);
            OnQuickJoinFailed?.Invoke(this, EventArgs.Empty);
        }
    }

    public async void JoinWithCode(string lobbyCode)
    {
        OnJoinStarted?.Invoke(this, EventArgs.Empty);

        try
        {
            _JoinedLobby = await LobbyService.Instance.JoinLobbyByCodeAsync(lobbyCode);

            KitchenGameMultiplayer.Instance.StartClient();
        }
        catch (LobbyServiceException e)
        {
            Debug.LogException(e);
            OnJoinFailed?.Invoke(this, EventArgs.Empty);
        }
    }

    public async void JoinWithId(string lobbyId)
    {
        OnJoinStarted?.Invoke(this, EventArgs.Empty);

        try
        {
            _JoinedLobby = await LobbyService.Instance.JoinLobbyByIdAsync(lobbyId);

            KitchenGameMultiplayer.Instance.StartClient();
        }
        catch (LobbyServiceException e)
        {
            Debug.LogException(e);
            OnJoinFailed?.Invoke(this, EventArgs.Empty);
        }
    }

    public async void DeleteLobby()
    {
        if (_JoinedLobby != null)
        {
            try
            {
                await LobbyService.Instance.DeleteLobbyAsync(_JoinedLobby.Id);

                _JoinedLobby = null;
            }
            catch (LobbyServiceException e)
            {
                Debug.LogException(e);
            }
        }
    }

    public async void LeaveLobby()
    {
        if (_JoinedLobby != null)
        {
            if (_JoinedLobby.Players.Count == 1)
            {
                DeleteLobby();
                return;
            }


            try
            {
                await LobbyService.Instance.RemovePlayerAsync(_JoinedLobby.Id, AuthenticationService.Instance.PlayerId);

                _JoinedLobby = null;
            }
            catch (LobbyServiceException e)
            {
                Debug.LogException(e);
            }
        }
    }

    public async void KickPlayer(string playerId)
    {
        if (IsLobbyHost())
        {
            try
            {
                await LobbyService.Instance.RemovePlayerAsync(_JoinedLobby.Id, playerId);
            }
            catch (LobbyServiceException e)
            {
                Debug.LogException(e);
            }
        }
    }

    public Lobby GetLobby()
    {
        return _JoinedLobby;            
    }
}
